#!/usr/bin/env tsx
/**
 * Pre-build codegen: scans src/tools/*.ts for mcpTools/figmaHandlers exports
 * and generates barrel registry files. Run before tsup build.
 *
 * Usage: tsx scripts/generate-registries.ts
 */

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const TOOLS_DIR = join(__dirname, "..", "src", "tools");
const SKIP = new Set(["helpers.ts", "schemas.ts", "types.ts", "prompts.ts"]);

// Discover tool modules — track MCP and Figma exports separately
const mcpModules: string[] = [];
const figmaModules: string[] = [];
for (const file of readdirSync(TOOLS_DIR).sort()) {
  if (!file.endsWith(".ts")) continue;
  if (SKIP.has(file)) continue;
  if (file.startsWith("_") || file.includes(".generated.")) continue;
  if (file === "mcp-registry.ts" || file === "figma-registry.ts") continue;

  const content = readFileSync(join(TOOLS_DIR, file), "utf8");
  const name = file.replace(".ts", "");
  if (content.includes("export const mcpTools")) mcpModules.push(name);
  if (content.includes("export const figmaHandlers")) figmaModules.push(name);
}

const modules = [...new Set([...mcpModules, ...figmaModules])];
console.error(`[codegen] Found ${modules.length} tool modules (${mcpModules.length} MCP, ${figmaModules.length} Figma): ${modules.join(", ")}`);

// Camel-case helper: "create-frame" → "createFrame"
function camel(name: string): string {
  return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

// ─── Generate MCP Registry ──────────────────────────────────────

const mcpImports = mcpModules
  .map((m) => `import { mcpTools as ${camel(m)}Tools } from "./${m}";`)
  .join("\n");

const mcpSpreads = mcpModules
  .map((m) => `  ...${camel(m)}Tools,`)
  .join("\n");

const mcpRegistry = `// Auto-generated by scripts/generate-registries.ts — DO NOT EDIT
import type { McpServer, SendCommandFn } from "./types";
import { mcpJson, mcpError } from "./types";
import type { ToolDefinition } from "./types";
import { registerPrompts } from "./prompts";

${mcpImports}

const ALL_TOOLS: ToolDefinition[] = [
${mcpSpreads}
];

/** Register all MCP tools and prompts on the server */
export function registerAllTools(server: McpServer, sendCommand: SendCommandFn) {
  for (const tool of ALL_TOOLS) {
    const cmd = tool.commandName || tool.name;
    const timeout = tool.timeoutMs;

    if (tool.handler) {
      server.tool(tool.name, tool.description, tool.schema, async (params: any) => {
        try {
          return await tool.handler!(params, sendCommand);
        } catch (e) {
          return mcpError(\`Error in \${tool.name}\`, e);
        }
      });
    } else if (tool.responseType === "image") {
      server.tool(tool.name, tool.description, tool.schema, async (params: any) => {
        try {
          const result = await sendCommand(cmd, params, timeout) as any;
          return { content: [{ type: "image" as const, data: result.imageData, mimeType: result.mimeType }] };
        } catch (e) {
          return mcpError(\`Error in \${tool.name}\`, e);
        }
      });
    } else {
      server.tool(tool.name, tool.description, tool.schema, async (params: any) => {
        try {
          return mcpJson(await sendCommand(cmd, params, timeout));
        } catch (e) {
          return mcpError(\`Error in \${tool.name}\`, e);
        }
      });
    }
  }

  registerPrompts(server);
}
`;

// ─── Generate Figma Registry ────────────────────────────────────

const figmaImports = figmaModules
  .map((m) => `import { figmaHandlers as ${camel(m)}Handlers } from "./${m}";`)
  .join("\n");

const figmaSpreads = figmaModules
  .map((m) => `  ...${camel(m)}Handlers,`)
  .join("\n");

const figmaRegistry = `// Auto-generated by scripts/generate-registries.ts — DO NOT EDIT
${figmaImports}

/** Merged dispatch map: command name → handler function */
export const allFigmaHandlers: Record<string, (params: any) => Promise<any>> = {
${figmaSpreads}
};
`;

// ─── Write files ────────────────────────────────────────────────

const mcpPath = join(TOOLS_DIR, "_mcp-registry.generated.ts");
const figmaPath = join(TOOLS_DIR, "_figma-registry.generated.ts");

writeFileSync(mcpPath, mcpRegistry);
writeFileSync(figmaPath, figmaRegistry);

console.error(`[codegen] Generated ${mcpPath}`);
console.error(`[codegen] Generated ${figmaPath}`);
